server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/system_server?useUnicode=true&useSSL=false&characterEncoding=utf8
    password: 123456
    username: root
mybatis-plus:
  mapper-locations: classpath:/mappings/*Mapper.xml
